version: "3.8"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PORT: 6379

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dg_site
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
